dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - sha256sum -c build/bazel_0.3.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
  - bazel test -c opt //eidos/...

