dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-7

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.2.1/bazel_1.2.1-linux-x86_64.deb
  - sha256sum -c build/bazel_1.2.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_1.2.1-linux-x86_64.deb

script:
  - bazel test -c opt //eidos/...

