name: "linux"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test-ubuntu:
    name: Build and Test (Ubuntu)
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64

    steps:
    - uses: actions/checkout@v2

    - name: Free up some space in an image
      run: |
        # This doesn't seem to affect the speed of the run, but takes ~2 minutes,
        # commented out for now.
        #sudo rm -rf /usr/share/dotnet
        #sudo rm -rf /opt/ghc
        df -h

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE.bazel') }}
        restore-keys: ${{ runner.os }}-bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/latest/download/$BAZEL"
        chmod +x $BAZEL

    - name: Install sox
      run: apt-get update && apt-get install -y sox

    - name: Build
      run: ./$BAZEL build -c opt //build/... //eidos/...

    - name: Test
      run: ./$BAZEL test -c opt --test_output=errors //build/... //eidos/...
