name: "macos"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test-macos:
    name: Build and Test (macOS)
    runs-on: macos-latest
    env:
      BAZEL: bazelisk-darwin-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Update environment variables
      run: |
        echo "USER=${USER}" >> ${GITHUB_ENV}

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: /private/var/tmp/_bazel_${{ env.USER }}
        key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE.bazel') }}
        restore-keys: ${{ runner.os }}-bazel

    - name: Install bazelisk
      run: |
        curl -sLO "https://github.com/bazelbuild/bazelisk/releases/latest/download/$BAZEL"
        chmod +x $BAZEL

    - name: Build
      run: ./$BAZEL build -c opt //build/... //eidos/...

    - name: Test
      run: ./$BAZEL test -c opt --test_output=errors //... //build/... //eidos/...
